# -*- coding: utf-8 -*-
"""btc_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19i7ctcDwFps_gzwYpHo3El6Ga5i9T_6i
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/FYP_DATA/'
df = pd.read_csv(drive_path + 'Bitcoin_Price_PreProcessing.csv')

df.head(5)

df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year

df.tail(5)

df.info()

df.shape

"""**1- Graph shows the Bitcoin closing price over years**"""

plt.figure(figsize=(14, 5))
plt.plot(df['Date'], df['Close'], color='#F7931A', linewidth=1.2)
plt.fill_between(df['Date'], df['Close'], alpha=0.15, color='#F7931A')
plt.title('Bitcoin Close Price (2018–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x:,.0f}'))
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""**2- Graph shows the Annual Returns of Bitcoin**"""

annual = []
for year in sorted(df['Year'].unique()):
    yd = df[df['Year'] == year]
    ret = ((yd['Close'].iloc[-1] - yd['Close'].iloc[0]) / yd['Close'].iloc[0]) * 100
    annual.append({'Year': int(year), 'Return': ret})

annual_df = pd.DataFrame(annual)

plt.figure(figsize=(12, 6))
colors = ['#2ecc71' if r > 0 else '#e74c3c' for r in annual_df['Return']]
bars   = plt.bar(annual_df['Year'].astype(str), annual_df['Return'],
                 color=colors, edgecolor='white', width=0.6)
plt.axhline(0, color='black', linewidth=1.5)

for bar, ret in zip(bars, annual_df['Return']):
    ypos = bar.get_height() + 4 if ret > 0 else bar.get_height() - 18
    plt.text(bar.get_x() + bar.get_width()/2, ypos,
             f'{ret:+.0f}%', ha='center', fontsize=11, fontweight='bold',
             color='#27ae60' if ret > 0 else '#c0392b')

plt.title('Bitcoin Annual Returns (2018–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Return (%)')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

"""**3- Graph shows the Label Distribution**"""

label_counts = df['Label'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie([label_counts[0], label_counts[1]],
        labels=[f'DOWN\n{label_counts[0]} days', f'UP\n{label_counts[1]} days'],
        colors=['#e74c3c', '#2ecc71'],
        autopct='%1.1f%%',
        startangle=90,
        explode=(0.03, 0.03),
        textprops={'fontsize': 13},
        wedgeprops={'edgecolor': 'white', 'linewidth': 2})

plt.title('Label Distribution — UP vs DOWN Days', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**4- Graph shows the RSI_14 Day Value**"""

plt.figure(figsize=(14, 5))
plt.plot(df['Date'], df['RSI_14'], color='purple', linewidth=0.9)
plt.axhline(70, color='red',   linestyle='--', linewidth=1.5, label='Overbought (70)')
plt.axhline(30, color='green', linestyle='--', linewidth=1.5, label='Oversold (30)')
plt.fill_between(df['Date'], 70, 100, alpha=0.07, color='red')
plt.fill_between(df['Date'], 0,  30,  alpha=0.07, color='green')
plt.ylim(0, 100)
plt.title('RSI_14 Day (2018–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('RSI Value')
plt.legend(fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""**5- Graph shows the RSI Zones vs Average Next-Day Return**"""

df['RSI_Zone'] = pd.cut(df['RSI_14'],
                         bins=[0, 30, 50, 70, 100],
                         labels=['Oversold\n(0–30)', 'Bearish\n(30–50)',
                                 'Bullish\n(50–70)', 'Overbought\n(70–100)'])

zone_avg = df.groupby('RSI_Zone', observed=True)['Log_Return'].mean() * 100
colors_z = ['#2ecc71', '#95a5a6', '#3498db', '#e74c3c']

plt.figure(figsize=(11, 6))
bars = plt.bar(zone_avg.index, zone_avg.values,
               color=colors_z, edgecolor='white', width=0.5)
plt.axhline(0, color='black', linewidth=1.5)

for bar, val in zip(bars, zone_avg.values):
    ypos = val + 0.002 if val >= 0 else val - 0.004
    plt.text(bar.get_x() + bar.get_width()/2, ypos,
             f'{val:+.4f}%', ha='center', fontsize=11, fontweight='bold')

plt.title('Average Next-Day Return by RSI Zone', fontsize=14, fontweight='bold')
plt.xlabel('RSI Zone')
plt.ylabel('Avg Log Return (%)')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

"""**6- Graph shows the Feature Correlation with Label**"""

feature_cols = ['RSI_14', 'MACD_Hist', 'ADX', 'ATR_14', 'BB_Width',
                'MFI', 'CMF', 'ROC_10', 'CCI', 'CO_Ratio',
                'Log_Return', 'Volatility_7', 'OBV', 'STOCH_K']

corr = df[feature_cols + ['Label']].corr()['Label'].drop('Label').sort_values()

plt.figure(figsize=(10, 8))
colors_c = ['#e74c3c' if v < 0 else '#2ecc71' for v in corr.values]
plt.barh(corr.index, corr.values, color=colors_c, edgecolor='white', height=0.6)
plt.axvline(0, color='black', linewidth=1.5)

for i, val in enumerate(corr.values):
    xpos = val + 0.002 if val >= 0 else val - 0.002
    ha   = 'left' if val >= 0 else 'right'
    plt.text(xpos, i, f'{val:+.3f}', va='center', ha=ha, fontsize=9)

plt.title('Feature Correlation with Price Direction', fontsize=14, fontweight='bold')
plt.xlabel('Correlation Coefficient')
plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

"""**7- Graph shows the Average Indicator Values UP vs DOWN Days**"""

indicators = ['RSI_14', 'MACD_Hist', 'ROC_10', 'CO_Ratio', 'BB_Width', 'Volatility_7']

df_melt = df[indicators + ['Label']].melt(id_vars='Label',
                                           var_name='Indicator',
                                           value_name='Value')
df_melt['Direction'] = df_melt['Label'].map({1: 'UP', 0: 'DOWN'})

g = sns.FacetGrid(df_melt, col='Indicator', col_wrap=3,
                  height=4, aspect=1.1, sharey=False)
g.map_dataframe(sns.boxplot, x='Direction', y='Value',
                palette={'UP': '#2ecc71', 'DOWN': '#e74c3c'},
                width=0.5, fliersize=2, linewidth=0.8)
g.set_titles(col_template='{col_name}', size=12, fontweight='bold')
g.set_axis_labels('', 'Value')

for ax in g.axes.flat:
    ax.grid(True, alpha=0.3, axis='y')

g.figure.suptitle('Indicator Distribution: UP vs DOWN Days',
                   fontsize=14, fontweight='bold', y=1.02)
g.tight_layout()
plt.show()

"""**8- Graph shows the Rolling Volatility Over Time**"""

plt.figure(figsize=(14, 5))
plt.plot(df['Date'], df['Volatility_7'], color='crimson', linewidth=0.9)
plt.fill_between(df['Date'], df['Volatility_7'], alpha=0.2, color='crimson')
plt.axhline(df['Volatility_7'].mean(), color='black', linestyle='--',
            linewidth=1.5, label=f"Mean: {df['Volatility_7'].mean():.4f}")
plt.title('7-Day Rolling Volatility (2018–2025)', fontsize=14, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Volatility')
plt.legend(fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""**9- Graph shows the Volatility Regime vs Signal Reliability**"""

df['Vol_Regime'] = pd.cut(df['Volatility_7'], bins=3,
                           labels=['Low', 'Medium', 'High'])

regime = df.groupby('Vol_Regime', observed=True).agg(
    UP_pct   = ('Label', 'mean'),
    Total    = ('Label', 'count')
).reset_index()
regime['UP_pct']   *= 100
regime['DOWN_pct']  = 100 - regime['UP_pct']

fig, ax = plt.subplots(figsize=(12, 6))
y_pos   = [2, 1, 0]
height  = 0.35
colors_r = ['#3498db', '#f39c12', '#e74c3c']

for i, row in regime.iterrows():
    ax.barh(y_pos[i] + height/2, row['UP_pct'],
            height=height, color='#2ecc71', edgecolor='white')
    ax.barh(y_pos[i] - height/2, row['DOWN_pct'],
            height=height, color='#e74c3c', edgecolor='white')
    ax.text(row['UP_pct']/2,   y_pos[i] + height/2,
            f"UP: {row['UP_pct']:.1f}%",
            ha='center', va='center', fontsize=12,
            fontweight='bold', color='white')
    ax.text(row['DOWN_pct']/2, y_pos[i] - height/2,
            f"DOWN: {row['DOWN_pct']:.1f}%",
            ha='center', va='center', fontsize=12,
            fontweight='bold', color='white')
    ax.text(102, y_pos[i], f"n={int(row['Total'])}",
            va='center', fontsize=11, fontweight='bold')
    ax.text(-1, y_pos[i], f"{row['Vol_Regime']} Volatility",
            ha='right', va='center', fontsize=12,
            fontweight='bold', color=colors_r[i])

ax.axvline(51.2, color='black', linestyle='--', linewidth=2)
ax.set_xlim(0, 100)
ax.set_ylim(-0.6, 2.8)
ax.set_yticks([])
ax.set_xlabel('Percentage (%)', fontsize=12)
ax.grid(True, alpha=0.3, axis='x')

patches = [mpatches.Patch(color='#2ecc71', label='UP Days'),
           mpatches.Patch(color='#e74c3c', label='DOWN Days'),
           plt.Line2D([0],[0], color='black', linestyle='--', label='Avg (51.2%)')]
ax.legend(handles=patches, fontsize=11, loc='lower right')
ax.set_title('Volatility Regime vs Signal Reliability', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

"""**10- Graph show the coorelation between indicators**"""

key_features = ['RSI_14', 'MACD_Hist', 'ADX', 'ATR_14',
                'BB_Width', 'CMF', 'CO_Ratio', 'Log_Return',
                'Volatility_7', 'ROC_10', 'Label']

corr_matrix = df[key_features].corr()

plt.figure(figsize=(13, 10))
sns.heatmap(corr_matrix,
            annot=True,
            fmt='.2f',
            cmap='RdYlGn',
            vmin=-1, vmax=1,
            linewidths=0.5,
            annot_kws={'size': 10},
            square=True)

plt.title('Feature Correlation Heatmap', fontsize=14, fontweight='bold', pad=15)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.savefig(drive_path + 'Graph_10_Heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

