# -*- coding: utf-8 -*-
"""btc preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcxZkSKcRQ2T5kgl8hDkl3iLl0rQ4dpz
"""

!pip install pandas numpy ta matplotlib plotly -q

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
df_btc = pd.read_csv('/content/drive/MyDrive/FYP_DATA/Bitcoin_Price_Data.csv', skiprows=1)

df_btc.head()

df_btc.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

df_btc.tail()

df_btc['Date'] = pd.to_datetime(df_btc['Date'])

df_btc = df_btc.sort_values('Date').reset_index(drop=True)

for col in ['Close', 'High', 'Low', 'Open', 'Volume']:
    df_btc[col] = pd.to_numeric(df_btc[col], errors='coerce')

df_btc.head()

df_btc.shape

df_btc.info()

df_btc.describe()

df_btc.isnull().sum()

import ta

df = df_btc.copy()
df.shape

# Adding the TREND INDICATORS
df['SMA_10'] = ta.trend.sma_indicator(df['Close'], window=10)
df['SMA_20'] = ta.trend.sma_indicator(df['Close'], window=20)
df['SMA_50'] = ta.trend.sma_indicator(df['Close'], window=50)

df['EMA_10'] = ta.trend.ema_indicator(df['Close'], window=10)
df['EMA_20'] = ta.trend.ema_indicator(df['Close'], window=20)

df['MACD']        = ta.trend.macd(df['Close'])
df['MACD_Signal'] = ta.trend.macd_signal(df['Close'])
df['MACD_Hist']   = ta.trend.macd_diff(df['Close'])

df['ADX'] = ta.trend.adx(df['High'], df['Low'], df['Close'])

df.shape

# Adding the MOMENTUM INDICATORS
df['RSI_14'] = ta.momentum.rsi(df['Close'], window=14)

df['STOCH_K'] = ta.momentum.stoch(df['High'], df['Low'], df['Close'])
df['STOCH_D'] = ta.momentum.stoch_signal(df['High'], df['Low'], df['Close'])

df['WILLIAMS_R'] = ta.momentum.williams_r(df['High'], df['Low'], df['Close'])

df['ROC_10'] = ta.momentum.roc(df['Close'], window=10)

df['CCI'] = ta.trend.cci(df['High'], df['Low'], df['Close'])

df.shape

#Adding the VOLATILITY INDICATORS
df['BB_Upper']  = ta.volatility.bollinger_hband(df['Close'])
df['BB_Lower']  = ta.volatility.bollinger_lband(df['Close'])
df['BB_Width']  = ta.volatility.bollinger_wband(df['Close'])
df['BB_Middle'] = ta.volatility.bollinger_mavg(df['Close'])

df['ATR_14'] = ta.volatility.average_true_range(
    df['High'], df['Low'], df['Close'])

df.shape

# Adding the VOLUME INDICATORS
df['OBV'] = ta.volume.on_balance_volume(df['Close'], df['Volume'])

df['MFI'] = ta.volume.money_flow_index(
    df['High'], df['Low'], df['Close'], df['Volume'])

df['CMF'] = ta.volume.chaikin_money_flow(
    df['High'], df['Low'], df['Close'], df['Volume'])

df['VWAP'] = ta.volume.volume_weighted_average_price(
    df['High'], df['Low'], df['Close'], df['Volume'])

df.shape

# Adding the PRICE DERIVED FEATURES
df['HL_Ratio'] = (df['High'] - df['Low']) / df['Close']

df['CO_Ratio'] = (df['Close'] - df['Open']) / df['Open']

df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))

df['Volatility_7']  = df['Log_Return'].rolling(window=7).std()
df['Volatility_14'] = df['Log_Return'].rolling(window=14).std()

df['Volume_SMA_7'] = ta.trend.sma_indicator(df['Volume'], window=7)

df.shape

df['Label'] = (df['Close'].shift(-1) > df['Close']).astype(int)
df.shape

df = df.dropna().reset_index(drop=True)
df = df[:-1].reset_index(drop=True)
df.shape

df.isnull().sum()

df['Label'].value_counts()

df[['Close', 'RSI_14', 'MACD',
          'ATR_14', 'BB_Width',
          'Log_Return', 'Label']].describe()

drive_path = '/content/drive/MyDrive/FYP_DATA/'

df.to_csv(
    drive_path + 'Bitcoin_Price_PreProcessing.csv',
    index=False
)

df = pd.read_csv(
    '/content/drive/MyDrive/FYP_DATA/Bitcoin_Price_PreProcessing.csv')

df.shape

